# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
title:            Clark To Do
tagline:          'The blog of Clark'
description:      '<p><a href="http://weibo.com/u/1802092940" target="_blank">@clarkdo</a></p> <p>Clark Blog </p>'
url:              http://clarkdo.github.io/
paginate:         5
paginate_path:    "page:num"

author:
  name:           'Clark Du'
  url:            http://weibo.com/u/1802092940

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/clarkdo/clarkdo.github.com
