# Dependencies
markdown:         kramdown
highlighter:      rouge

# Permalinks
permalink:        pretty

# Setup
baseurl:          "https://clarkdo.js.org/"
title:            Clark To Do
tagline:          'The blog of Clark'
description:      '<p><a href="//www.weibo.com/u/2127101144" target="_blank">@clarkdo</a></p> <p>Clark Blog </p>'
url:              https://clarkdo.js.org/
paginate: 10
paginate_path: "page:num"
excerpt_separator: "\n\n\n"

author:
  name:           'Clark Du'
  url:            //www.weibo.com/u/2127101144

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/clarkdo/clarkdo.github.com
