# Dependencies
markdown:         redcarpet
redcarpet:
    extensions: ["tables"]
highlighter:      pygments

# Permalinks
permalink:        pretty

# Setup
baseurl:          "http://clarkdo.github.io/"
title:            Clark To Do
tagline:          'The blog of Clark'
description:      '<p><a href="http://www.weibo.com/u/2127101144" target="_blank">@clarkdo</a></p> <p>Clark Blog </p>'
url:              http://clarkdo.github.io/
paginate: 10
paginate_path: "page:num"
excerpt_separator: "\n\n\n"

author:
  name:           'Clark Du'
  url:            http://www.weibo.com/u/2127101144

# Custom vars
version:          1.0.0

github:
  repo:           https://github.com/clarkdo/clarkdo.github.com
